- name: K8S Worker Deploybook
  hosts: all
  become: yes
  gather_facts: no
  vars_prompt:
    - name: k8s_version
      prompt: "Kubernetes version"
      default: latest
      private: no

  tasks:
    - name: K8S Cluster network module
      lineinfile:
        path: /etc/modules-load.d/k8s.conf
        line: br_netfilter
        state: present
        create: yes
    - name: K8S Cluster network sysctl
      blockinfile:
        path: /etc/sysctl.d/k8s.conf
        block: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
        state: present
        create: yes
    - name: K8S Cluster network configuration apply
      shell:
        cmd: sysctl --system

    - name: Containerd network module
      blockinfile:
        path: /etc/modules-load.d/containerd.conf
        block: |
          overlay
          br_netfilter
        state: present
        create: yes
    - name: Containerd overlay module activation
      shell:
        cmd: modprobe overlay
    - name: Containerd br_netfilter module activation    
      shell:
        cmd: modprobe br_netfilter
    - name: K8S Container Runtime Interface(cri) configuration
      blockinfile: 
        path: /etc/sysctl.d/99-kubernetes-cri.conf
        block: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1
        state: present
        create: yes
    - name: Containerd network configuration apply
      shell:
        cmd: sysctl --system

    - name: APT Update - Upgrade
      apt:
        name: "*"
        state: latest
        update_cache: yes
    - name: Install containerd
      apt:
        name: containerd
        state: present
    - name: Create folder for containerd
      file:
        path: /etc/containerd
        owner: root
        group: root
        mode: "0644"
        state: directory
    - name: Configuration for containerd
      shell: 
        cmd: containerd config default | tee /etc/containerd/config.toml
    - name: Restart containerd
      service:
        name: containerd
        state: restarted
    
    - name: APT Update
      apt:
        update_cache: yes
    - name: Pre-required packages
      apt:
        pkg:
        - apt-transport-https
        - ca-certificates
        - curl
    - name: K8S packages keys
      shell:
        cmd: curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
    - name: K8S APT repo addresses
      shell:
        cmd: echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
    - name: APT Update
      apt:
        update_cache: yes
    - name: Install kubelet
      apt:
        name: kubelet
        state: "{{k8s_version}}"
    - name: Install kubeadm
      apt:
        name: kubeadm
        state: "{{k8s_version}}"
    - name: Install kubectl
      apt:
        name: kubectl
        state: "{{k8s_version}}"
    - name: Hold kubelet
      dpkg_selections:
        name: kubelet
        selection: hold
    - name: Hold kubeadm
      dpkg_selections:
        name: kubeadm
        selection: hold
    - name: Hold kubectl
      dpkg_selections:
        name: kubectl
        selection: hold
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

